
class Autogenerated {
  Autogenerated({
      int? userId, 
      int? id, 
      String? title, 
      String? body,}){
    _userId = userId;
    _id = id;
    _title = title;
    _body = body;
}

  Autogenerated.fromJson(dynamic json) {
    _userId = json['userId'];
    _id = json['id'];
    _title = json['title'];
    _body = json['body'];
  }
  int? _userId;
  int? _id;
  String? _title;
  String? _body;

  int? get userId => _userId;
  int? get id => _id;
  String? get title => _title;
  String? get body => _body;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['userId'] = _userId;
    map['id'] = _id;
    map['title'] = _title;
    map['body'] = _body;
    return map;
  }
}

// class Autogenerated {
//   int? userId;
//   int? id;
//   String? title;
//   String? body;

//   Autogenerated({
//     this.userId,
//     this.id,
//     this.title,
//     this.body,
//   });

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     userId = json['userId'] as int?;
//     id = json['id'] as int?;
//     title = json['title'] as String?;
//     body = json['body'] as String?;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> json = <String, dynamic>{};
//     json['userId'] = userId;
//     json['id'] = id;
//     json['title'] = title;
//     json['body'] = body;
//     return json;
//   }
// }